input {
  beats {
    port => 5044
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown-service" }
    }
  }

  if ![instance] {
    mutate {
      add_field => { "instance" => "unknown-instance" }
    }
  }

  if ![traceId] {
    mutate {
      add_field => { "traceId" => "NO_TRACE" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "msa-logs-%{service}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}