filebeat.inputs:
  - type: filestream
    id: spring-json-logs
    enabled: true
    paths:
      - /logs/*/*/app.json
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true

processors:
  - add_host_metadata: {}
  - add_docker_metadata: {}

output.logstash:
  hosts: ["logstash:5044"]