server:
  port: 9000

spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          ignore-local-ssh-settings: true
          private-key: ${GIT_PRIVATE_KEY}